/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sneb.struts.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.sneb.bean.Account;

/**
 * MyEclipse Struts Creation date: 11-28-2016
 * 
 * XDoclet definition:
 * 
 * @struts.form name="accountForm"
 */
public class AccountForm extends ActionForm {
	/*
	 * Generated fields
	 */
	/** demo property */
	private String demo;

	/** operateType property */
	private String operateType;

	/** userPwd property */
	private String userPwd;

	/** userId property */
	private String userId;

	/** userMobile property */
	private String userMobile;

	/** userEmail property */
	private String userEmail;

	private List<Account> listAccount;

	private Integer id;

	private String remoteIp;

	private String userRealname;

	public String getUserRealname() {
		return userRealname;
	}

	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname;
	}

	public String getRemoteIp() {
		return remoteIp;
	}

	public void setRemoteIp(String remoteIp) {
		this.remoteIp = remoteIp;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public List<Account> getListAccount() {
		return listAccount;
	}

	public void setListAccount(List<Account> listAccount) {
		this.listAccount = listAccount;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the demo.
	 * 
	 * @return String
	 */
	public String getDemo() {
		return demo;
	}

	/**
	 * Set the demo.
	 * 
	 * @param demo
	 *            The demo to set
	 */
	public void setDemo(String demo) {
		this.demo = demo;
	}

	/**
	 * Returns the operateType.
	 * 
	 * @return String
	 */
	public String getOperateType() {
		return operateType;
	}

	/**
	 * Set the operateType.
	 * 
	 * @param operateType
	 *            The operateType to set
	 */
	public void setOperateType(String operateType) {
		this.operateType = operateType;
	}

	/**
	 * Returns the userPwd.
	 * 
	 * @return String
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * Set the userPwd.
	 * 
	 * @param userPwd
	 *            The userPwd to set
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	/**
	 * Returns the userId.
	 * 
	 * @return String
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * Set the userId.
	 * 
	 * @param userId
	 *            The userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Returns the userMobile.
	 * 
	 * @return String
	 */
	public String getUserMobile() {
		return userMobile;
	}

	/**
	 * Set the userMobile.
	 * 
	 * @param userMobile
	 *            The userMobile to set
	 */
	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	/**
	 * Returns the userEmail.
	 * 
	 * @return String
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * Set the userEmail.
	 * 
	 * @param userEmail
	 *            The userEmail to set
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}
}